// A small, focused prompt for a coach-authored group session -- distinct
// from buildSystemPrompt (prompts.ts), which expects a structured
// WorkoutContext/prescription this doesn't have. The input here is already
// the coach's own specific free text, not a category to retrieve reference
// content for, so no retrieval step either.
export function buildGroupWorkoutExplanationPrompt(input: {
  description: string;
  workoutType: string | null;
  phaseDisplayName: string | null;
  phasePrimaryGoal: string | null;
}): string {
  const phaseContext =
    input.phaseDisplayName || input.phasePrimaryGoal
      ? `Training phase: ${input.phaseDisplayName ?? "unspecified"}.${
          input.phasePrimaryGoal ? ` This phase's goal: ${input.phasePrimaryGoal}.` : ""
        }`
      : "No season phase context is available for this entry.";

  return `You are helping a high school cross country coach explain one of their own written training sessions to their athletes.

The coach wrote this session themselves -- it is not generated by you, and you must not invent numbers, distances, or paces that aren't already in it.

Session description (the coach's own words): "${input.description}"
${input.workoutType ? `Classified as: ${input.workoutType}.` : ""}
${phaseContext}

Write 2-3 short, plain-language sentences explaining what this specific session is for and what an athlete should expect to feel -- grounded in the training phase context above when it's relevant. Do not restate the description verbatim. Do not mention specific paces or distances unless the coach's own description already includes them. Do not use headers, bullet points, or labels -- just the sentences themselves, ready to show an athlete directly.`;
}
